apiVersion: v1
data:
  images.json: |-
    [
      "https://i.imgflip.com/7jqevq.jpg",
      "https://i.imgflip.com/7jqekl.jpg",
      "https://i.imgflip.com/7jmwjs.jpg",
      "https://www.mye-work.com/web/mye-work/images/myework-logo.png"
    ]
kind: ConfigMap
metadata:
  name: images-json
  labels:
    app: random-meme
